name: Pipeline Tests
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@v4

      - name: Run actions/setup-node
        run: echo "Run actions/setup-node"

      - name: Install Dependencies
        run: echo "Install Dependencies"

      - name: Typecheck + Lint + Test Coverage
        run: echo "Typecheck + Lint + Test Coverage"

      - name: Configure AWS Credentils
        run: echo "Configure AWS Credentils"

      - name: Migrate TypeORM
        run: echo "Migrate TypeORM"

      - name: Servelss Deploy
        run: echo "Servelss Deploy"

  trigger-common:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Automation test API/E2E
        uses: andreyLobo0/PipelineAutomationTest/.github/workflows/staging.yml@main
