name: Build e Deployment
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@v4

      - name: Run actions/setup-node
        run: echo "Run actions/setup-node"

      - name: Install Dependencies
        run: echo "Install Dependencies"

      - name: Typecheck + Lint + Test Coverage
        run: echo "Typecheck + Lint + Test Coverage"

      - name: Configure AWS Credentils
        run: echo "Configure AWS Credentils"

      - name: Migrate TypeORM
        run: echo "Migrate TypeORM"

      - name: Servelss Deploy
        run: echo "Servelss Deploy"

      - name: Trigger E2E Tests Repository
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: andreyLobo0/PipelineAutomationTest
          event-type: e2e-tests-triggered
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
